---
version: 3
interval: 1000ms
output: prefixed

tasks:
  default:
    cmds:
      - task: build
      - task: test

  build:
    aliases:
      - b
    desc: Build the Cloud Function
    summary: |-
      Build the Cloud Function so it can be tested or packaged.
    cmds:
      - cmd: echo "building..."

  test:
    aliases:
      - t
    desc: Test the Cloud Function
    summary: |-
      Test the Cloud Function to validation that is will operate as expected.
    deps:
      - task: build
    cmds:
      - cmd: echo "testing..."

  lint:
    aliases:
      - l
    desc: Lint the Cloud Function via golangci-lint
    summary: |-
      Lint to GoLang files for the Cloud Function using golangci-lint to check
      the code quality, and run prettier and other linters over any JSON and
      YAML files for the infrastructure code.
    sources:
      - 'main.go'
      - '**/*.go'
      - '../.golangci.yaml'
    cmds:
      - cmd: |-
          golangci-lint run \
            --config=../.golangci.yaml \
            --path-prefix=function

  clean:
    aliases:
      - c
    desc: Clean up the Cloud Function temporary files and directories
    summary: |-
      Clean up any known temporary files and directories within the repository
      that have been created either by the Cloud Function development.
    run: once
    cmds:
      - cmd: rm -rf .task
