---
version: 3
interval: 1000ms
output: prefixed

tasks:
  default:
    cmds:
      - task: lint
      - task: plan

  fmt:
    aliases:
      - f
    desc: Properly format all .go files for the CDKTF Infrastructure as Code
    summary: |-
      Properly fomrmat all of the .go files for the CDKTF Infrastructure as Code
      using go (this is a write-based action which will make changes to all .go
      files, if required).
    sources:
      - '**/*.go'
    cmds:
      - cmd: go fmt ./...

  lint:
    aliases:
      - l
    desc: Lint the IaC via golangci-lint
    summary: |-
      Lint to GoLang files for the Infrastuecture as Code using golangci-lint to
      check the code quality, and run prettier and other linters over any JSON
      and YAML files for the infrastructure code.
    deps:
      - task: fmt
    sources:
      - 'main.go'
      - '**/*.go'
      - '../.golangci.yaml'
    cmds:
      - cmd: |-
          golangci-lint run \
            --config=../.golangci.yaml \
            --path-prefix=infra

  test:
    aliases:
      - t
    desc: Test the CDKTF Infrastructure as Code
    summary: |-
      Test the CDKTF Infrastructure as Code to validation that is will operate
      as expected.
    deps:
      - task: lint
    sources:
      - '**/*.go'
    cmds:
      # If this taskfile is being run inside of tmux, tell tmux to send the
      # Enter key to the same pane as it is running in so that it exits
      # scrolling mode and starts refreshing the screen as new tests are run
      - cmd: |-
          test -n "$TMUX_PANE" && tmux send-keys -t $TMUX_PANE Enter
        silent: true
      - cmd: |-
          go test -v ./... \
            -covermode=count \
            -coverprofile=coverage.out
      - cmd: |-
          go tool cover \
            -func=coverage.out
      - cmd: |-
          go tool cover \
            -html=coverage.out \
            -o=coverage.html
        silent: true

  synth:
    aliases:
      - s
    desc: Build the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code for testing or deployment.
    deps:
      - task: lint
    cmds:
      - cmd: echo "synthesising..."

  # plan does not require synth as a dependency as plan will re-run the
  # synthesis of the IaC when it runs anyway
  plan:
    aliases:
      - p
    desc: Plan the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code, then run a plan against it to show the expected
      changes to the infrastructure.
    deps:
      - task: lint
    cmds:
      - cmd: echo "synthesising..."

  deploy:
    aliases:
      - s
    desc: Deploy the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code, then run a deploy against it to deploy the changes
      to the infrastructure to the environments.
    deps:
      - task: lint
    cmds:
      - cmd: echo "synthesising..."

  clean:
    aliases:
      - c
    desc: Clean up the Infrastructure temporary files and directories
    summary: |-
      Clean up any known temporary files and directories within the repository
      that have been created either via the Infrastruce as Code management with
      CDKTF.
    run: once
    cmds:
      - cmd: rm -rf coverage/*/* coverage.out
      - cmd: rm -rf .task
