---
version: 3
interval: 1000ms
output: prefixed

vars:
  base: github.com/n3tuk/infra-gcp-function
  deploy: ../dist/deploy
  coverage: .coverage
  modules:
    sh: |-
      go list ./... 2>/dev/null \
      | grep -v infra/generated \
      | sed -e 's|^{{ .base }}/||'

tasks:
  default:
    cmds:
      - task: test

  fmt:
    aliases:
      - f
    desc: Properly format all .go files for the CDKTF Infrastructure as Code
    summary: |-
      Properly format all of the .go files for the CDKTF Infrastructure as Code
      using go (this is a write-based action which will make changes to all .go
      files, if required).
    # Configure the sources to exclude counting the pre-generated code created
    # by CDKTF as triggers, as there is no need to run fmt against this code.
    deps:
      - task: get
    sources:
      - '**/*.go'
      - exclude: 'generated/**/*.go'
    cmds:
      - for:
          var: modules
          as: module
        cmd: |-
          go fmt {{.base }}/{{ .module }}

  lint:
    aliases:
      - l
    desc: Lint the IaC via golangci-lint
    summary: |-
      Lint to GoLang files for the Infrastuecture as Code using golangci-lint to
      check the code quality, and run prettier and other linters over any JSON
      and YAML files for the infrastructure code.
    deps:
      - task: get
    # Like for the fmt task above, ensure we do not count changes due to the
    # pre-generated code created by CDKTF, as these do not need to be checked.
    sources:
      - '../.golangci.yaml'
      - '**/*.go'
      - exclude: 'generated/**/*.go'
    cmds:
      - cmd: |-
          golangci-lint run \
            --config=../.golangci.yaml \
            --path-prefix=infra \
            --verbose

  test:
    aliases:
      - t
    desc: Test the CDKTF Infrastructure as Code
    summary: |-
      Test the CDKTF Infrastructure as Code to validation that is will operate
      as expected.
    deps:
      # There is not dependency on linting for this task, as may normally be the
      # case, as linting requires processing all Provider bindings and can take
      # a long time to complete, needlessly delaying this step in CI.
      - task: get
    # Include the pre-generated code from CDKTF as triggers; we want to be able
    # to test changes against this code, as well as changes to this code as too.
    sources:
      - '**/*.go'
    cmds:
      # If this task is being run inside of tmux, tell tmux to send the Enter
      # key to the same pane this is running in so that it exits scrolling mode
      # as the new tests are run. This can, at times, leave a rouge empty-line
      # in the output, but it ensures the latest tests are shown as they run.
      - cmd: |-
          ( test -n "$TMUX_PANE" \
            && tmux send-keys -t $TMUX_PANE Enter
          ) || true
        silent: true
      - cmd: |-
          mkdir -p {{ .coverage }}
        silent: true
      - for:
          var: modules
          as: module
        cmd: |-
          go test -v -cover {{.base }}/{{ .module }} \
            -args -test.gocoverdir="{{ .TASKFILE_DIR }}/{{ .coverage }}"
      - cmd: |-
          go tool covdata func -i {{ .coverage }}
      # Convert all the data into an HTML page for easy viewing of code coverage
      - cmd: |-
          go tool covdata textfmt -i {{ .coverage }} -o coverage.out
          go tool cover -html coverage.out -o coverage.html
        silent: true

  get:
    aliases:
      - init
    desc: Get and process the Terraform bindings
    summary: |-
      Get and process the Terraform Provider and Terraform Module bindings for
      the Infrastructure as Code.
    sources:
      - 'cdktf.json'
    cmds:
      - cmd: |-
          ../node_modules/.bin/cdktf get

  synth:
    desc: Build the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code for testing or deployment.
    deps:
      # There is no dependency on linting nor testing for this task as both of
      # these can take a long time to process due to the Provider bindings.
      - task: get
    sources:
      - 'cdktf.json'
      - '**/*.go'
    cmds:
      - cmd: |-
          mkdir -p {{ .deploy }}
        silent: true
      - cmd: |-
          ../node_modules/.bin/cdktf get \
            --output {{ .deploy }}

  diff:
    aliases:
      - plan
    desc: Create a diff (plan) for the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code, then run a diff against it to show the expected
      changes to the infrastructure (i.e. a plan).
    deps:
      - task: synth
    sources:
      - 'cdktf.json'
      - '**/*.go'
    cmds:
      - cmd: |-
          mkdir -p {{ .deploy }}
        silent: true
      - cmd: |-
          ../node_modules/.bin/cdktf diff \
            --skip-synth \
            --output {{ .deploy }}

  deploy:
    aliases:
      - apply
    desc: Deploy the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code, then run a deploy against it to deploy the changes
      to the infrastructure to the environments.
    deps:
      - task: synth
    sources:
      - 'cdktf.json'
      - '**/*.go'
    cmds:
      - cmd: |-
          mkdir -p {{ .deploy }}
        silent: true
      - cmd: |-
          ../node_modules/.bin/cdktf deploy \
            --skip-synth \
            --auto-approve \
            --output {{ .deploy }}

  destroy:
    desc: Deploy the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code, then run a deploy against it to deploy the changes
      to the infrastructure to the environments.
    deps:
      # Although this is a destroy step, just like normal HCL-based Terraform
      # configurations, we need the configuration of the Providers in order to
      # connect to the endpoints and destroy those resources in the state file.
      - task: synth
    cmds:
      - cmd: |-
          mkdir -p {{ .deploy }}
        silent: true
      - cmd: |-
          ../node_modules/.bin/cdktf destroy \
            --output {{ .deploy }}

  clean:
    desc: Clean up the temporary files and directories for CDKTF and the Stacks
    summary: |-
      Clean up any known temporary files and directories within the repository
      that have been created either via CDKTF for the Infrastruce as Code and
      the Stacks.
    run: once
    cmds:
      - cmd: rm -rf {{ .deploy }}
      - cmd: rm -rf {{ .coverage }} coverage.{out,html}
      - cmd: rm -rf .task
