---
version: 3
interval: 1000ms
output: prefixed

tasks:
  default:
    cmds:
      - task: lint
      - task: plan

  lint:
    aliases:
      - l
    desc: Lint the IaC via golangci-lint
    summary: |-
      Lint to GoLang files for the Infrastuecture as Code using golangci-lint to
      check the code quality, and run prettier and other linters over any JSON
      and YAML files for the infrastructure code.
    sources:
      - 'main.go'
      - '**/*.go'
      - '../.golangci.yaml'
    cmds:
      - cmd: |-
          golangci-lint run \
            --config=../.golangci.yaml

  synth:
    aliases:
      - s
    desc: Build the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code for testing or deployment.
    cmds:
      - cmd: echo "synthesising..."

  plan:
    aliases:
      - p
    desc: Plan the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code, then run a plan against it to show the expected
      changes to the infrastructure.
    cmds:
      - cmd: echo "synthesising..."

  deploy:
    aliases:
      - s
    desc: Deploy the Infrastucture as Code
    summary: |-
      Build and run the CDKTF application to synthesise the Terraform JSON
      Infrastructure as Code, then run a deploy against it to deploy the changes
      to the infrastructure to the environments.
    cmds:
      - cmd: echo "synthesising..."

  clean:
    aliases:
      - c
    desc: Clean up the Infrastructure temporary files and directories
    summary: |-
      Clean up any known temporary files and directories within the repository
      that have been created either via the Infrastruce as Code management with
      CDKTF.
    run: once
    cmds:
      - cmd: rm -rf .task
