---
name: Go Integrations

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: read
  actions: read
  pull-requests: read
  security-events: write

jobs:
  linting:
    strategy:
      matrix:
        module:
          - 'function'
          - 'infra'
        platform:
          - ubuntu-latest
      fail-fast: false

    name: golangci Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.module }}
          args: --config=../.golangci.yaml --path-prefix=${{ matrix.module }}

  testing:
    strategy:
      matrix:
        version:
          - '1.20'
          - '1.21'
          - '1.22'
        module:
          - 'function'
          - 'infra'
        platform:
          - 'ubuntu-latest'
      fail-fast: false
    needs:
      - linting

    name: Go Tests
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up Go v${{ matrix.version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: Verify the Go modules
        working-directory: ${{ matrix.module }}
        run: go mod verify

      - name: Download the Go modules
        working-directory: ${{ matrix.module }}
        run: go mod download

      - name: Run standard tests
        working-directory: ${{ matrix.module }}
        run: go test -v ./...

      - name: Run race tests
        working-directory: ${{ matrix.module }}
        run: go test -v -race ./...
