---
name: Go Integrations

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: read
  actions: read
  pull-requests: read
  security-events: write

jobs:
  linting:
    strategy:
      matrix:
        module:
          - 'function'
          - 'infra'
        platform:
          - ubuntu-latest
      fail-fast: false

    name: golangci Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install the bingo tool
        run: |-
          go install \
            github.com/bwplotka/bingo@latest

      - name: Install the required Go tools
        run: bingo get --link

      - name: Install CDKTF and the required NodeJS tools
        run: |-
          yarn install \
            --ignore-engines \
            --no-progress

      - name: Lint the ${{ matrix.module }} Go module
        working-directory: ${{ matrix.module }}
        run: |-
          task lint \
            --output group \
            --output-group-begin '::group::{{ .TASK }}' \
            --output-group-end '::endgroup::'\

  testing:
    strategy:
      matrix:
        version:
          - '1.20'
          - '1.21'
        module:
          - 'function'
          - 'infra'
        platform:
          - 'ubuntu-latest'
      fail-fast: false
    needs:
      - linting

    name: Go Tests
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up Go v${{ matrix.version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install the bingo tool
        run: |-
          go install \
            github.com/bwplotka/bingo@latest

      - name: Install the required Go tools
        run: |-
          bingo get --link

      - name: Install CDKTF and the required NodeJS tools
        run: |-
          yarn install \
            --ignore-engines \
            --no-progress

      - name: Test the ${{ matrix.module }} Go module
        working-directory: ${{ matrix.module }}
        run: |-
          task test \
            --output group \
            --output-group-begin '::group::{{ .TASK }}' \
            --output-group-end '::endgroup::'\
