---
name: Go Integrations

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: read
  actions: read
  pull-requests: read
  security-events: write

jobs:
  testing:
    strategy:
      matrix:
        version:
          - '1.19'
          - '1.20'
          - '1.21'
        folder:
          - 'function'
          - 'infra'
        platform:
          - 'ubuntu-latest'
      fail-fast: false

    name: Go Tests
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Set up Go v${{ matrix.version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.version }}
          cache-dependency-path: go.sum

      - name: Verify the Go modules
        working-directory: ${{ matrix.folder }}
        run: go mod verify

      - name: Download the Go modules
        working-directory: ${{ matrix.folder }}
        run: go mod download

      - name: Run standard tests
        working-directory: ${{ matrix.folder }}
        run: go test -v ./...

      - name: Run race tests
        working-directory: ${{ matrix.folder }}
        run: go test -v -race ./...

  linting:
    strategy:
      matrix:
        folder:
          - 'function'
          - 'infra'
        platform:
          - ubuntu-latest
      fail-fast: false

    name: golangci Linting
    runs-on: ubuntu-latest
    needs:
      - testing
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.folder }}
          args: --config=../.golangci.yaml
